
export const VIEW_PAGE = 'VIEW_PAGE';
export const FETCH_INTROPAGES_SUCCESS = "FETCH_INTROPAGES_SUCCESS";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILED = "FETCH_COURSES_FAILED";
export const FETCH_INTROPAGES_FAIL = "FETCH_INTROPAGES_FAIL";

export const SITE_IS_OFFLINE = "SITE_IS_OFFLINE";
export const SITE_IS_ONLINE = "SITE_IS_ONLINE";
export const PAGES_INIT = "PAGES_INIT";
export const PAGE_INFO = "PAGE_INFO";

export const CONTACT_US_CHANGE_NAME = "CONTACT_US_CHANGE_NAME"
export const CONTACT_US_CHANGE_EMAIL = "CONTACT_US_CHANGE_EMAIL"
export const CONTACT_US_CHANGE_DESC = "CONTACT_US_CHANGE_DESC"

// export const PAGE_VIEWER_SELECTED = "PAGE_VIEWER_SELECTED"
export const PAGE_VIEWER_CATEGORY_SELECTED = "PAGE_VIEWER_CATEGORY_SELECTED"
export const PAGE_VIEWER_INIT_RECEIVE = "PAGE_VIEWER_INIT_RECEIVE"
export const PAGE_VIEWER_INIT_REQUEST = "PAGE_VIEWER_INIT_REQUEST"
export const PAGE_VIEWER_INIT_REQUEST_FAILED = "PAGE_VIEWER_INIT_REQUEST_FAILED"

export const CATEGORY_VIEWER_INIT_RECEIVE = "CATEGORY_VIEWER_INIT_RECEIVE"
export const CATEGORY_VIEWER_INIT_REQUEST = "CATEGORY_VIEWER_INIT_REQUEST"
export const CATEGORY_VIEWER_INIT_REQUEST_FAILED = "CATEGORY_VIEWER_INIT_REQUEST_FAILED"

export const CONTENT_INIT = "CONTENT_INIT"
export const CONTENT_REQUEST = "CONTENT_REQUEST"
export const CONTENT_REQUEST_FAILED = "CONTENT_REQUEST_FAILED"
export const CONTENT_RECEIVE = "CONTENT_RECEIVE"

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
export const USER_LOGOUT = "USER_LOGOUT"

